version: '2'

services:

  build:
    build:
      context: .
    image: beachfront:base

  bash:
    image: beachfront:base
    entrypoint: /bin/bash
    volumes:
      - './:/work'

  test:
    image: beachfront:base
    entrypoint: bash -c 'nosetests test -v -s'
    volumes:
      - './:/work'
