version: '2'

services:

  build:
    build:
      context: .
    image: beachfront-py

  bash:
    image: beachfront-py
    entrypoint: /bin/bash
    volumes:
      - '.:/work:rw'

  test:
    image: beachfront-py
    command: bash -c 'nosetests -v -s;'
    working_dir: /work
    volumes:
      - '.:/work:rw'
